Crudweb/Controllers/ProductController.cs
using AutoMapper;
using CRUD.Domain.Employee;
using CRUD.EF;
using CRUDWeb.Models;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Mvc;
using System.Net.WebSockets;
using X.PagedList;

namespace CRUDWeb.Controllers
{
    public class ProductController : Controller
    {
        private readonly ProductDbContext context;
        private readonly IProductService productService;
        private readonly IMapper mapper;
        private readonly IWebHostEnvironment webHostEnvironment;
        public ProductController(IProductService _productService, ProductDbContext _context, IMapper _mapper, IWebHostEnvironment _env)
        {
            productService = _productService;
            webHostEnvironment = _env;
            context = _context;
            mapper = _mapper;

        }
        public async Task<IActionResult> Index(int? page, string searchString, string sortOrder)
        {
            ViewBag.NameSortParm = String.IsNullOrEmpty(sortOrder) ? "name_desc" : "";
            ViewData["CurrentFilter"] = searchString;
            var products = await productService.GetAllProducts();
            var prod1 = from s in products select s;
            if (!String.IsNullOrEmpty(searchString))
            {
                prod1 = prod1.Where(s => s.ProductName.Contains(searchString) || s.Brand.Contains(searchString));
            }
            switch (sortOrder)
            {
                case "firstname_desc":
                    prod1 = prod1.OrderByDescending(e => e.ProductName);
                    break;
                default:
                    prod1 = prod1.OrderBy(e => e.ProductName);
                    break;
            }
            int pageSize = 3;
            int pageNumber = (page ?? 1);

            var prod2 = prod1.ToPagedList(pageNumber, pageSize);
            var prod3 = prod2.ToList();

            return View(prod2);
        }
        public async Task<IActionResult> Post(ProductRequestModel prodview)
        {
            var DTOmapped = mapper.Map<Product>(prodview);
            return Ok(DTOmapped);
        }
        public IActionResult Add()
        {
            return View();
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Add(ProductRequestModel prod)
        {
            if (ModelState.IsValid)
            {
                var product = mapper.Map<Product>(prod);
                string wwwRootPath = webHostEnvironment.WebRootPath;
                if (prod.Image != null)
                {
                    string fileName = "images/img/";
                    fileName += Guid.NewGuid().ToString() + Path.GetExtension(prod.Image.FileName);
                    string serverfolder = Path.Combine(wwwRootPath, fileName);
                    await prod.Image.CopyToAsync(new FileStream(serverfolder, FileMode.Create));
                    product.ImageURL = "/" + fileName;

                }
                             
                await productService.AddProduct(product);
                TempData["Success"] = "Product Registered Successfully!";
                return RedirectToAction("Index");
            }
            return View(prod);
        }
        public async Task<IActionResult> Edit(Guid? id)
        {
            if (id == null)
            {
                return NotFound();
            }
            var prod = await productService.GetProductById(id.Value);
            if (prod == null)
            {
                return NotFound();
            }
            var prod1 = mapper.Map<ProductRequestModel>(prod);
            return View(prod1);
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(Guid id, ProductRequestModel prod)
        {
            if (ModelState.IsValid)
            {
                var existingProduct = await productService.GetProductById(id);
                if (existingProduct == null)
                {
                    return NotFound();
                }
                mapper.Map(prod, existingProduct);
                
                if (prod.Image != null)
                {
                    string folder = "images/";
                    folder += Guid.NewGuid().ToString() + "_" + prod.Image.FileName;
                    string serverfolder = Path.Combine(webHostEnvironment.WebRootPath, folder);
                    using (var fileStream = new FileStream(serverfolder, FileMode.Create))
                    {
                        await prod.Image.CopyToAsync(fileStream);
                    }
                    existingProduct.ImageURL = "/" + folder;
                }
                await productService.EditProduct(existingProduct);
                TempData["Success"] = "Product Record Updated Successfully!";
                return RedirectToAction("Index");
            }
            return View(prod);
        }
        public async Task<IActionResult> Delete(Guid? id)
        {
            if (id == null)
            {
                return NotFound();
            }
            var prod = await productService.GetProductById(id.Value);
            if (prod == null)
            {
                return NotFound();
            }
            var prod1 = mapper.Map<ProductRequestModel>(prod);
            return View(prod1);
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Delete(Product prod)
        {
            await productService.DeleteProduct(prod);

            TempData["Success"] = "Product Record Deleted Successfully!";
            return RedirectToAction("Index");          
        }
    }
}

Crudweb/Controllers/ShoppingCartController.cs
using CRUD.Domain.Employee;
using CRUD.Domain.Product;
using CRUD.EF;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace CRUDWeb.Controllers
{
    public class ShoppingCartController : Controller
    {
        private readonly IProductService productService;
        private readonly IShoppingCartService shoppingCartService;

        public ShoppingCartController(IProductService _productService, IShoppingCartService _shoppingCartService)
        {
            productService = _productService;
            shoppingCartService = _shoppingCartService;
        }
        public async Task<IActionResult> Index()
        {
            var cartFromDb = await shoppingCartService.GetAllItems();
            return View(cartFromDb);
        }

        public async Task<IActionResult> RemoveItem(Guid id)
        {
            var cart = await shoppingCartService.GetCartById(id);
            var cartFromDb = await shoppingCartService.RemoveFromCart(cart);
            TempData["Success"] = "Item Removed Successfully!";
            return RedirectToAction("Index");
        }

        public async Task<IActionResult> Plus(Guid id)
        {
            var cartFromDb = await shoppingCartService.GetCartById(id);
            cartFromDb.TotalItems += 1;
            await shoppingCartService.UpdateCart(cartFromDb);
            return RedirectToAction("Index");
        }
        public async Task<IActionResult> Minus(Guid id)
        {
            var cartFromDb = await shoppingCartService.GetCartById(id);
            if(cartFromDb.TotalItems <= 1)
            {
                await shoppingCartService.RemoveFromCart(cartFromDb);
            }
            else
            {
                cartFromDb.TotalItems -= 1;
                await shoppingCartService.UpdateCart(cartFromDb);
            }
            
            return RedirectToAction("Index");
        }
    }
}

Crudweb/Views/Shared/_Layout.cshtml
@using CRUD.EF
@inject ProductDbContext dbContext;
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - ProductDemoWeb</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/css/BootsWatchTheme.css" .css" />
    <link rel="stylesheet" href="~/EmployeeDemoWeb.styles.css" asp-append-version="true" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.2.1/css/all.min.css">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.10.3/font/bootstrap-icons.css">
    <link rel="stylesheet" href="//cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.css" />

</head>
<body>
    <header>
        <nav class="navbar navbar-expand-lg navbar-dark bg-primary">
          
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Catalog</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarColor01" aria-controls="navbarColor01" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div>
                    <a class="navbar-brand" asp-area="" asp-controller="ShoppingCart" asp-action="Index"><i class="fa-solid fa-cart-shopping"></i>(@(dbContext.ShoppingCartTable.Count()))</a>
                </div>
                <div class="collapse navbar-collapse" id="navbarColor01">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link" asp-area="" asp-controller="Product" asp-action="Index">Products</a>
                        </li>

                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                                More
                            </a>
                            <ul class="dropdown-menu">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Product" asp-action="Index">Products</a>
                                <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Catalog</a>
                                <li><hr class="dropdown-divider"></li>
                            </ul>
                        </li>

                    </ul>
                </div>
                <div class="nav-search">
                    <form class="d-flex">
                    <input id="mysearch" class="form-control me-sm-2" type="text" name="SearchString" value="@ViewData["CurrentFilter"]" placeholder="Search">
                    <button class="btn btn-secondary" type="submit">Search</button>
                </form>
                </div>
                

            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>
    <script>
        $("#mysearch").on("keyup", function () {
            var value = $(this).val().toLowerCase();
            $("#tableid tr").filter(function () {
                $(this).toggle($(this).text().toLowerCase().indexOf(value) > -1);
            });
        });</script>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.6.4/jquery.min.js"></script>
    <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/sweetalert/2.1.2/sweetalert.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.6.4/jquery.min.js"></script>
    <script src="https://cdn.tiny.cloud/1/nhc37793pt0s7aa9hmae96v9b9ymol792yicg2uemfks0use/tinymce/6/tinymce.min.js" referrerpolicy="origin"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

Crudweb/Views/Shared/_Notification.cshtml
@if (TempData["success"] != null)
{
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="//cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.js"></script>
    <script type="text/javascript">
        toastr.success('@TempData["success"]');
    </script>

}
@if (TempData["error"] != null)
{
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="//cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.js"></script>
    <script type="text/javascript">
        toastr.error('@TempData["error"]');
    </script>
}
